### ISSUE TITLE
Unsupported regions shown for instance families

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#45]
Got error message when starting an campaign "Failed to Request spot fleet" and below is CloudWatch log I got. Any idea why this would happen?

2022-04-07T04:30:53.995Z	INFO	Failed to request spot fleet. InvalidSpotFleetRequestConfig: Invalid: (InstanceType: g5g.xlarge with Os: Linux/UNIX and EC2-VPC),(InstanceType: g5g.xlarge with Os: Linux/UNIX and EC2-VPC),(InstanceType: g5g.xlarge with Os: Linux/UNIX and EC2-VPC)
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidSpotFleetRequestConfig',
  time: 2022-04-07T04:30:53.994Z,
  requestId: '',
  statusCode: 400,
  retryable: false,
  retryDelay: 72.47257896273831
}

**Comment by c6fc** [comment]
Try a different region. It seems that the API throws InvalidSpotFleetRequestConfig when you try to pick an instance family that isn't supported in a specified region. If this is the case, I'll add constraints to that unsupported regions don't show up in the selector.

**Comment by bzekanovic** [comment]
Seems like different region works, but might be confusing for end users when they start the campaign.

**Comment by c6fc** [comment]
Added in dev

**Comment by bzekanovic** [comment]
When do you think you can merge latest updates into main?

**Comment by c6fc** [comment]
merged
