### ISSUE TITLE
Changing Primary Region when you don't have quota

### ISSUE THREAD

**Issue by VladRico** [c6fc/npk#57]
Hi !

As you asked me, there is an issue when a user try to change the primary region when he doesn't have the right GPU quota :

`npm run configure`
```
? Which region do you plan to use most? eu-west-1
? What is the admin user's email address? npk@xxx
? Enter an SMS-enabled phone number for critical events, including country code: xxx
? Max campaign price in USD: 50
? NPK is configured. Deploy now? Yes
[+] Retrieved all active regions
[+] Retrieved quotas.
[+] Retrieved per-region instance support.
[+] Retrieved availability zones.

[*] All prerequisites finished. Generating infrastructure configurations.
[+] Using bootstrap bucket sonnetry-shnprltxj-1651576289
Trace: Error: Error parsing Jsonnet file: JsonnetError: RUNTIME ERROR: field does not exist: eu-west-1
        terraform.jsonnet:410:16-56     thunk <a>
        terraform.jsonnet:(408:33)-(411:6)      function <anonymous>
        terraform.jsonnet:(408:33)-(411:6)      thunk <value>
        std.jsonnet:952:9-14    thunk <v>
        std.jsonnet:919:10      thunk <a>
        std.jsonnet:919:10-19   function <anonymous>
        std.jsonnet:919:10-19   function <aux>
        std.jsonnet:952:5-23    function <anonymous>
        terraform.jsonnet:(408:14)-(411:11)     object <anonymous>
        terraform.jsonnet:(405:15)-(413:5)      object <anonymous>
        terraform.jsonnet:(404:16)-(414:4)      object <config>
        jsonnet/lambda.libsonnet:(6:12)-(13:5)  object <anonymous>
        jsonnet/lambda.libsonnet:(5:24)-(14:4)  object <anonymous>
        jsonnet/lambda.libsonnet:(4:12)-(64:3)  object <anonymous>
        terraform.jsonnet:(399:37)-(462:4)      object <anonymous>
        During manifestation

    at exports.Sonnet.render (/aws/mde/npk/node_modules/@c6fc/sonnetry/src/index.js:346:10)
    at async deploy (/aws/mde/npk/bin/index.js:224:3)
    at async Object.handler (/aws/mde/npk/bin/index.js:487:20)
    at deploy (/aws/mde/npk/bin/index.js:226:11)
    at async Object.handler (/aws/mde/npk/bin/index.js:487:20)

[!] Failed to generate NPK configurations.
```
As you said : `I need to fix the primaryRegion prompt to only show regions where there's sufficient quota.`

Have a nice day ;)

**Comment by c6fc** [comment]
This has been addressed in 'dev'
